### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by mihai-iorga** [node-apn/node-apn#518]
I am trying for several days to figure out the following error:

    Warning: Possible EventEmitter memory leak detected. 11 wakeup listeners added. Use emitter.setMaxListeners() to increase limit
        at _addListener (events.js:259:19)
        at Connection.addListener (events.js:275:10)
        at Connection.Readable.on (_stream_readable.js:687:35)
        at Connection.once (events.js:301:8)
        at Connection._send (/opt/push/server/releases/20170202150908/node_modules/http2/lib/protocol/connection.js:356:10)
        at runCallback (timers.js:649:20)
        at tryOnImmediate (timers.js:622:5)
        at processImmediate [as _immediateCallback] (timers.js:594:5)`

After a long period of debugging (not that memory leaks warnings are debug-able), I think I found from where this error is coming from, server is up and no warnings in the last 24 hours.

I have added after [this._connection](https://github.com/node-apn/node-apn/blob/master/lib/protocol/endpoint.js#L83):

`this._connection.setMaxListeners(0);`

I know this is not the solution (infinite listeners is a bad idea), but I am tired of figuring out what the hell is happening there, maybe a second pair of eyes can see the leak.

GNU/Linux
NodeJS 6.9.4
NPM 3.10.10

I do not have a reproducible code that emits that warning because it happens once every now and then.
If this only happens to me, then my bad, sorry.

**Comment by haozxuan** [comment]
@mihai-iorga I have this Warning too, because InternalServerError i update module version 2.1.1 to 2.1.3, InternalServerError is gone, but this Warning make me worry about this module stable? if no perfect solution i will back to 2.1.1 and use pem file. :|

**Comment by jdrydn** [comment]
Yeah, I'm debugging a `TopicDisallowed` error whilst trying to migrate to the auth-key workflow of APNS, and I've just hit this too by leaving my script running (after printing the error) for 10 minutes or so. Given my push notification process stays alive for weeks at a time this is enough of a reason to continue using `apn@1.7`.

**Comment by jdrydn** [comment]
Hmm. Given this:

```js
var apn = require('apn');
var path = require('path');

var service = new apn.Provider({
  token: {
    key: path.join(__dirname, 'APNsAuthKey_KEY_ID.p8'),
    keyId: 'KEY_ID',
    teamId: 'TEAM_ID',
  },
  production: true,
});

while(true) {}
```

No warnings about memory leaks appears. But update that to send a single notification:

```js
var apn = require('apn');
var path = require('path');

var service = new apn.Provider({
  token: {
    key: path.join(__dirname, 'APNsAuthKey_KEY_ID.p8'),
    keyId: 'KEY_ID',
    teamId: 'TEAM_ID',
  },
  production: true,
});

var notification = new apn.Notification();
notification.topic = 'com.someimportantcompany.myapp';
notification.alert = 'Hello, world!';

service.send(notification, 'push-notification-id').then(function (reply) {
  console.log(JSON.stringify(reply, null, 2));
});
```

I get a successful output, and roughly 10 minutes later I get the warning about a possible memory leak:


```
{
  "sent": [
    {
      "device": "push-notification-id"
    }
  ],
  "failed": []
}
(node) warning: possible EventEmitter memory leak detected. 11 wakeup listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Connection.addListener (events.js:239:17)
    at Connection.Readable.on (_stream_readable.js:680:33)
    at Connection.once (events.js:265:8)
    at Connection._send (/Users/james/Sites/apns-test/node_modules/http2/lib/protocol/connection.js:356:10)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

Given the error message is quite specific "`11 wakeup listeners added`" searching this repo for "`wakeup`" reveals the only place this event is listened on: https://github.com/node-apn/node-apn/blob/61495d2dd8c097d209f6820cad7f1cbfb3c6e063/lib/client.js#L14

```
function Client (options) {
    this.config = config(options);

    this.endpointManager = new EndpointManager(this.config);
    this.endpointManager.on("wakeup", () => {
        ...
    });

    ...
}
```

My guess would be `new Client()` is being called multiple times?

**Comment by jdrydn** [comment]
To add:

Sending to N devices in series doesn't impact on the number of listeners (after sending to 3 or 4 devices, 10ish minutes later the warning still appears stating "`11 wakeup listeners added`".

Sending a device token 1 notification every 30 seconds doesn't trigger any warnings at all, after 10ish minutes, suggesting it's related to inactivity?

Sending a device token 1 notification every 15 minutes triggers a warning after 10ish minutes *each time*.

Each time it's always "`11 wakeup listeners added`". I'm going to run this script for the rest of the afternoon and see how consistent it is. I've also added logging to determine if `new endpointManager` is actually being called repeatedly or not.

**Comment by jdrydn** [comment]
To also add:

Obviously this bug is coming from [this line](https://github.com/molnarg/node-http2/blob/2c4c310f414d3249421340c0e2618873b07c17cb/lib/protocol/connection.js#L339) in `http2`, if you see [this list of issues](https://github.com/molnarg/node-http2/issues?utf8=%E2%9C%93&q=is%3Aissue%20listeners) you can see it's happened to other people with other events and the only way they've solved it is with 'setMaxListeners(0)' to "fix" it.

Fortunately, this is only occurs because it's a `once` event. My guess is it goes from `10` to `11` at that moment, which is why it's never gone higher than 11 (for me, at least).

**Comment by mihai-iorga** [comment]
Nope, I think it's from NodeJS itself check [here](https://github.com/nodejs/node/issues/9268) and [here](https://github.com/nodejs/node/pull/9440).

The fix will land in Node 6.10.0 ..

**Comment by jeacott1** [comment]
+1 seeing this too.

**Comment by JacopoDaeli** [comment]
+1

**Comment by extempl** [comment]
Actually, not fixed in 7.5.0

**Comment by emretekince** [comment]
+1

**Comment by 5an1ty** [comment]
I have the same issue! node 7.5.

**Comment by edengol** [comment]
I switched to node 6.10.0 and still get the error using apn 2.1.3 some minutes after sending a notification.

**Comment by jacktuck** [comment]
Same issue 7.4.0

```2017-03-08T16:43:56.568176535Z (node:7) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 wakeup listeners added. Use emitter.setMaxListeners() to increase limit```

**Comment by debjeet-sarkar** [comment]
+1

**Comment by sbat** [comment]
+1

**Comment by emretekince** [comment]
I have just switched to Firebase.

**Comment by forz13** [comment]
node 6.10.0, apn 2.1.3   +1

**Comment by airs0urce** [comment]
node v7.7.1, apn 2.1.3 +1

**Comment by taina0407** [comment]
+1
node 6.10.0
apn 2.1.3

**Comment by didil** [comment]
👍

**Comment by forz13** [comment]
Anybody knows how to resolve this problem?

**Comment by jacktuck** [comment]
@forz13 Sounds like it comes from h2 module? So we can just wait for a fix upstream?

**Comment by DRSisco** [comment]
I was getting this error as well till I added:
```js
apnProvider.shutdown();
```
After I finished sending my notification.
Where apnProvider is my apn.Provider

**Comment by ShaharHD** [comment]
@DRSisco so you are creating and destroying new instances of apn.Provider every time you need to send a batch of notifications?

**Comment by DRSisco** [comment]
@ShaharHD In my solution I only create an apn.Provider when I need it. I falsely made the assumption that the apn.Provider was cleaned up by the garbage collector. This gave me the error in my project described by others above. "(node) warning: possible EventEmitter memory leak detected. 11 wakeup listeners added."
After I properly destroyed the apn.Provider when I wasn't using it, I never saw this warning again. This may not be your issue, but this fixed mine.

**Comment by debjeet-sarkar** [comment]
The previous version used to maintain a provider and re-connect whenever APNS threw an error. With this new version is it expected to create provider instances on demand and destroy it thereafter ?

**Comment by blerest** [comment]
When do you plan to fix this issue?

**Comment by alessiobacin** [comment]
I'm having the same problem here... hope someone fixes this soon

**Comment by ShaharHD** [comment]
@alessiobacin I actually looked into it.
So ... not that simple IMHO, for couple of reasons:

1. [HTTP2](https://github.com/molnarg/node-http2) is not maintained any more it seems (just look at molnarg/node-http2#222 which is almost 6 months old - which is what this project hot-fixed some of the issues (https://github.com/node-apn/node-http2)
2.  Node.JS is actually working on a new HTTP2 core at https://github.com/nodejs/http2 - but it is still in very early stages, although it started [here](https://github.com/nodejs/CTC/issues/6) almost a year ago.

So, my personal recommendation is to do as follows:
1. Use DB to group notifications (even a simple one like SQLite will work for this)
2. Have a scheduled event (once every X milliseconds or seconds) which will create a new instance of `node-apn` send all the notifications in batch and then release the instance.

**Comment by alessiobacin** [comment]
Hi ,
Thanks for you’re answer…
I foxed just doing apnProvider.shutdown();
After sending the messages.

Thanks and bye

Alessio Bacin
Cell. 393 4477555
bacin@newbiz.it<mailto:bacin@newbiz.it>

Newbiz s.r.l.
Corso Moncalieri 51
10131 - Torino (TO)
Tel 011 19838186
Fax 011 19837572
info@newbiz.it
www.newbiz.it

On 24 Apr 2017, at 15:47, Shahar Hadas <notifications@github.com<mailto:notifications@github.com>> wrote:

@alessiobacin I actually looked into it.
So ... not that simple IMHO, for couple of reasons:

• HTTP2 is not maintained any more it seems (just look at molnarg/node-http2#222 which is almost 6 months old - which is what this project hot-fixed some of the issues (https://github.com/node-apn/node-http2)
• Node.JS is actually working on a new HTTP2 core at https://github.com/nodejs/http2 - but it is still in very early stages, although it started here almost a year ago.
So, my personal recommendation is to do as follows:

• Use DB to group notifications (even a simple one like SQLite will work for this)
• Have a scheduled event (once every X milliseconds or seconds) which will create a new instance of node-apn send all the notifications in batch and then release the instance.

**Comment by jacktuck** [comment]
Might be worth trying latest h2, as this module runs on a fork
`https://github.com/node-apn/node-http2/archive/apn-2.1.4.tar.gz` whereas current is v3.3.6

**Comment by jacktuck** [comment]
Although, yeah, as @ShaharHD says looks unmaintained now :( There's a bunch of memory leak issues that are pending merge

**Comment by magicdawn** [comment]
token based Authentication is not supported well. 
https://github.com/sideshow/apns2/issues/42
Guess just switch back to cert way

**Comment by jacktuck** [comment]
Hopefully h2 makes core soon

**Comment by vitoxiajie** [comment]
Hi,I add " this._connection.emit('wakeup');" after [https://github.com/node-apn/node-apn/blob/master/lib/protocol/endpoint.js#L103](here),the warning message has gone.

**Comment by troypayne** [comment]
+1

**Comment by troypayne** [comment]
+1

**Comment by haozxuan** [comment]
@vitoxiajie work for me, i have run 1 month and no warming

**Comment by airs0urce** [comment]
@florianreinhart Is it possible that fix from @vitoxiajie will go to next release of apn module?

**Comment by neefrankie** [comment]
@vitoxiajie That does not solve the problem. I guess somewhere in the code too much event listeners are attached without removing them, preventing GC from releasing memory. We have hundreds of thousands device to send, and the process running node-apn quickly gobbles memory to Node's limit of around 1.6GB and it crashes. 
If you just have thousands of device to send, it might just take up several hundred MB of memory and eventually GC will recycle them.
See this article http://www.jongleberry.com/understanding-possible-eventemitter-leaks.html

**Comment by neefrankie** [comment]
Currently I solved this problem by passing `maxConnections: 2` to `Provider(options)`.
In the [endpointManager.js](https://github.com/node-apn/node-apn/blob/master/lib/protocol/endpointManager.js), it creates a connection pool and every connection has `wakeup` event attached to it. If you do not limit the size of the connection pool, chances are that the client might create a lot of connections when it cannot find any free connection. If you have a large array and every element in the array is attached the same event, you are taking a lot of memory and event in use prevent GC from recycling the memory.

Remember in browser you are recommended against writing codes in this way?
```js
for (let i = 0; i < 1000; i++) {
    htmlElement.addEventListener('evenName', handler);
}
```

The same principle applies to Node.js.

In the `endpointManager.js`, it does check the size of connection pool:
```js
if (this._currentConnection || this._endpoints.length >= this._config.maxConnections) {
      return;
}
```
It seems the docs forget to tell that there is a option named `maxConnections`.

**Comment by neefrankie** [comment]
Update: the above method dosn't work. It continues gobbling up memory and crashes.
```
ios-push      Mem: 1638 MB
```

**Comment by varungupta85** [comment]
I am running into this issue as well after upgrading from `1.x.x` to `2.1.4`.

**Comment by clarencetw** [comment]
I have the same problem

**Comment by neefrankie** [comment]
This issue might come from 2 sources:
1. Using too much events without removing them properly;
2. Two much concurrency while I/O cannot handle them as quickly as possible, the queue growing bigger and bigger and eventually using up memory.

I tried to read the source code of this repo and node-http2, and spdy-http2. But, like most js code, they are quite hard to read and reason about what is what. Finally, simply give up.

I switched to golang and everything works great. It is easy to write. The code is concise and clear.

**Comment by tmhenry** [comment]
Any plan to fix this?

**Comment by jacktuck** [comment]
Does anyone have a reproducible failing case? That would be a good starting point.

**Comment by neefrankie** [comment]
@jacktuck Well, yes before I switched most of work to golang. Now node.js is only responsible for rendering templates on our production server. Since the problem could only be reproduced on production with hundreds of thousands of actual push to APNs, I'm afraid I could not touch the production server with this module.

**Comment by jpike88** [comment]
Problem still occurs on node 8.5.0

For the love of god let's fix this... or at least have some proven workarounds that don't involve switching to Go XD

**Comment by VinceOPS** [comment]
Hi guys. Having the issue too with node v8.6.0 and apn 2.1.5.

**Comment by hthetiot** [comment]
> @ShaharHD Said
>> HTTP2 is not maintained any more it seems (just look at molnarg/node-http2#222 which is almost 6 months old - which is what this project hot-fixed some of the issues (https://github.com/node-apn/node-http2)
>>
>> Further more HTTP2 was done fast and dirty it seems in a Summer of Code program ... which makes it very hard to maintain IMO.
>>
>> Node.JS is actually working on a new HTTP2 core at https://github.com/nodejs/http2 - but it is still in very early stages, although it started here almost a year ago.

@ShaharHD, Regarding `molnarg/node-http2` that is non longer maintained, I just wanted to let  you know what we have created a fork that include all the fixes for the issues know to date available on npm and github.

The issue you refering to as been fixed here:
- Fixed here https://github.com/molnarg/node-http2/pull/222#issuecomment-324452939

# Original Source and Fork intent
> This NodeJS http2.js module version is a fork of node-http2 hosted on Github originally made by Gábor Molnár and available here: https://github.com/molnarg/node-http2
>
> This fork of node-http2 module named http2.js starts at version 4.0.0 in case previous the repository decides to pick up work again on version 3.x.x.
>
> We are aware that node 8.4.0 now has experimental http2 support via --expose-http2, and we will continue to support the full JavaScript implementation of http2.js at our discretion until HTTP/2 is more fully supported in a broad range of client platforms.
source: https://github.com/kaazing/http2.js#original-source-and-fork-intent

# More about `http2.js` 
- https://www.npmjs.com/package/http2.js
- https://github.com/kaazing/http2.js

Note about publisher: Kaazing Corp is the company that brought to you https://websocket.org.

**Comment by jpike88** [comment]
Just an FYI... kaazing/http2.js contains the extra commits that were made to node-apn/http2.js, so it should be good to test as is

**Comment by florianreinhart** [comment]
@jpike88 Please let us know if this fork fixes the memory leak issue for you.

**Comment by jpike88** [comment]
This is my testing code... going to run this and wait. Someone else said 10 mins the warning should show, let's see where it goes.

```
var apn = require('./');
var path = require('path');

var service = new apn.Provider({
  token: {
    key: path.join(__dirname, 'key.p8'),
    keyId:"xxxx",
    teamId: "xxxx"
  },
  production: true,
});

var notification = new apn.Notification();
notification.topic = 'xxxx';
notification.alert = '.';
service.send(notification, 'xxx').then(function (reply) {
  console.log(JSON.stringify(reply, null, 2));
});
service.send(notification, 'xxx').then(function (reply) {
  console.log(JSON.stringify(reply, null, 2));
});
service.send(notification, 'xxx').then(function (reply) {
  console.log(JSON.stringify(reply, null, 2));
});
service.send(notification, 'xxx').then(function (reply) {
  console.log(JSON.stringify(reply, null, 2));
});
service.send(notification, 'xxx').then(function (reply) {
  console.log(JSON.stringify(reply, null, 2));
});
service.send(notification, 'xxx').then(function (reply) {
  console.log(JSON.stringify(reply, null, 2));
});
service.send(notification, 'xxx').then(function (reply) {
  console.log(JSON.stringify(reply, null, 2));
});
service.send(notification, 'xxx').then(function (reply) {
  console.log(JSON.stringify(reply, null, 2));
});
service.send(notification, 'xxx').then(function (reply) {
  console.log(JSON.stringify(reply, null, 2));
});
service.send(notification, 'xxx').then(function (reply) {
  console.log(JSON.stringify(reply, null, 2));
});
service.send(notification, 'xxx').then(function (reply) {
  console.log(JSON.stringify(reply, null, 2));
});
service.send(notification, 'xxx').then(function (reply) {
  console.log(JSON.stringify(reply, null, 2));
});
service.send(notification, 'xxx').then(function (reply) {
  console.log(JSON.stringify(reply, null, 2));
});

service.send(notification, 'xxx').then(function (reply) {
  console.log(JSON.stringify(reply, null, 2));
});
```

**Comment by jpike88** [comment]
Ok, the above code DID trigger the memory leak warning within roughly 10 minutes. I will now use:

https://github.com/kaazing/http2.js/archive/v4.0.1.tar.gz

for the http2 package and see what happens. If I don't see the warning after one hour I'll let you all know.

**Comment by jpike88** [comment]
Can I please have permission to make a pull request?

**Comment by jpike88** [comment]
@hthetiot No luck, I still get the warning :(

**Comment by jpike88** [comment]
Perhaps this might be useful in helping debug the issue...

https://github.com/watson/event-debug

**Comment by hthetiot** [comment]
@jpike88 thanks for taking the time for testing http2.js
I will fill an issue on https://github.com/kaazing/http2.js and attempt to reproduce.
Keep you posted.

**Comment by dpmooney** [comment]
I've got the same issue, and have reproduced on both molnarg/node-http2 as well as kaazing/http2.js.  Mine comes after sending hundreds / thousands of notifications and is reproducible every time.

**Comment by jpike88** [comment]
Potentially relevant reading:

https://github.com/nodejs/http2/issues/108#issuecomment-301323264

Wonder if these things are related.

**Comment by airs0urce** [comment]
Btw, http2 module exposed by default in new node https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.8.0

**Comment by andreialecu** [comment]
If you can run node.js 8.8.1+, take a look at this comment:

https://github.com/node-apn/node-apn/issues/557#issuecomment-340812136

**Comment by jpike88** [comment]
@andreialecu Not an option for me, I use elastic beanstalk and it only supports 8.4.0. Would be good to know if its fixed though

**Comment by jpike88** [comment]
@andreialecu I can **CONFIRM** that the native http2 module in node 8.8.1 has fixed this issue using my earlier posted testing code... I'm not getting any event emitter warnings now after leaving it for almost a couple of hours.

So how do we get this fix to those on older versions?

**Comment by andreialecu** [comment]
@jpike88 Probably the most realistic solution would be to wait for 8.8.1+ to be available for you. The userland http2 module has too many quirks and issues, and maintenance has mostly stopped long ago.

**Comment by wong2** [comment]
But the http2 module in node is still in experimental stability?

**Comment by andreialecu** [comment]
@wong2 yes, but it works, and from my testing and from the plethora of stability issues reported here, it is incomparably more stable than the one being used by this package.

**Comment by jpike88** [comment]
If stability is a concern, how about some people here who have intense use cases try it out and put it through some heavy tests to confirm?

**Comment by jpike88** [comment]
Good news, 8.8.1 is now easily available in Elastic Beanstalk... awesome. Time to fork!

**Comment by jpike88** [comment]
For those who are using node-pushnotifications which depends on this library, and want this issue fixed NOW... you're in luck.

I have released a package that eliminates the memory leak issue by integrating the above node-apn-http2 package.

https://github.com/streaka/node-pushnotifications-http2

**Comment by odedsh** [comment]
This is not fixed on Node v8.9.1

Also https://github.com/andreialecu/node-apn-http2 fills my logs with warning that http2 is an experimental feature :/

**Comment by jpike88** [comment]
Weird, my logs are quiet now, I'm using 8.8.1...

Is your use case rather heavy?

And yes, that warning is unavoidable unless you put a --no-warnings flag in your production run script (which I don't do).

If the issue still occurs it might be time to notify the node.js team of a potential flaw.

**Comment by andreialecu** [comment]
@odedsh I assume you mean that using `node-apn` on 8.9.1 is not fixed, which it is not. 

`node-apn-http2` is a rewrite using native node http2  and should work properly, regardless of the warning.

**Comment by odedsh** [comment]
@jpike88 @andreialecu  I edited my comment cause it was not clear.  My logs are not quiet when I use the `node-apn` module. 

@jpike88 removing warnings is not an option at all. If I could suppress the warning for this single `require("http2")` call it would be nice

.

**Comment by jpike88** [comment]
@odedsh just an idea... you could maybe overload console.warn and regex for that warning message... and maybe have a timeout that checks to see if the message fired yet, and let you know when it doesn't so you can remove that override on a later version.

**Comment by andreialecu** [comment]
@odedsh a workaround for now might be this:

```
$ node --no-warnings <file>
```

```javascript
process.on('warning', (warning) => {
  if (warning.name == 'ExperimentalWarning' && warning.message == 'The http2 module is an experimental API.') {
    // suppressed
  } else {
    console.warn(`${warning.name}: ${warning.message}`);
  }
});
```

**Comment by andreialecu** [comment]
@odedsh Actually, I have released 1.1.0 of my module which has a workaround to disable the warning. See hideExperimentalHttp2Warning in the options at [node-apn-http2](https://www.npmjs.com/package/node-apn-http2)

Sorry for hijacking this, hope it helps someone.

**Comment by jpike88** [comment]
Have now been using [node-apn-http2](https://www.npmjs.com/package/node-apn-http2) for a while on production servers, logs are nice and quiet, and things are working fine. It's fixed as far as I'm concerned. It's a good excuse to also upgrade to 8.8.1+.

Good luck to the rest of you... but I wouldn't hold my breath waiting for this issue to be resolved.

**Comment by hsleep** [comment]
I have this issue too, so I decided to use [node-apn-http2](https://github.com/andreialecu/node-apn-http2) for the time being.

**Comment by florianreinhart** [comment]
@hsleep Have you tried the new 3.0.0 alpha release? This version uses the native node HTTP/2 client and should be in a better shape then node-apn-http2. It's intentionally labeled as alpha as long as node's HTTP/2 is still experimental.

**Comment by hsleep** [comment]
@florianreinhart I have not tested it yet. Because I do not know much about node-apn enough to use the alpha version for production. When I test the alpha version, I will let you know.

**Comment by mitolog** [comment]
new 3.0.0 alpha release as @florianreinhart mentioned gives no warning of 'EventEmitter memory leak...' and works fine for me. Thanks!

**Comment by vlasky** [comment]
Thanks @mitolog, updating to 3.0.0-alpha1 also appears to have resolved the EventEmitter memory leak issue in my webapp.

**Comment by christwsy** [comment]
@vlasky can you share the link for it? Appreciate. I'm trying to replace the node-http2 with the native one but no luck. Running node 8.9.1 lts.

**Comment by vlasky** [comment]
@christwsy 

https://github.com/node-apn/node-apn/releases/tag/v3.0.0-alpha1

**Comment by vlasky** [comment]
Unfortunately, our webapp was still experiencing random lockups even with v3.0.0-alpha1, so we've switched to [node-apn-http2](https://github.com/andreialecu/node-apn-http2).

**Comment by jpike88** [comment]
Just a reminder that I have a fork of this repo running with node-apn-http2 builtin... running with zero issues. Considering this issue is still open and people are trying to modernize, feel free to use this instead.

`npm install node-pushnotifications-http2`

https://github.com/streaka/node-pushnotifications-http2

**Comment by jpike88** [comment]
@vlasky can you describe your issue a little more?

@florianreinhart you should probably contact the guy who's maintaining node-apn-http2, it makes sense to get his approval and consider making his repo officially unmaintained. If he's happy to do it, I'm happy to test this one and modify my fork to point at it.

**Comment by florianreinhart** [comment]
@jpike88 Ah, I see. I thought you had created yet another node-apn fork.

The node-apn-http2 module isn't actually a fork of node-apn, but a rewrite in TypeScript with just the most basic features. The author had no interest to submit a PR for node-apn. That's why I adapted node's native HTTP/2 in 3.0.0-alpha1. It's labeled as an alpha, because node's HTTP/2 support is still experimental. 3.0.0-alpha1 has the same features as node-apn-http2 and more. I'd suggest you give it a try.

**Comment by jpike88** [comment]
Ah right, fair enough. I'll make some time next week to sort this out.

**Comment by andreialecu** [comment]
Hey, author of `node-apn-http2` here. 

It's not that I didn't want to submit a PR for `node-apn`, it's just that this module is a little too complex and it had the unofficial http2 module embedded deep within it, so adding node's http2 meant rewriting most of it - which I didn't have time to do - as it was breaking a critical app I was/am working on.

My module is meant to be super simple to reduce any potential bugs from edge cases deriving from the complexity of this one.

**Comment by jpike88** [comment]
Haha... would be great if you guys found a solution that would involve a rebase or whatever. Now I’m a little unsure of what to do here

**Comment by anthony-kenikh** [comment]
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 wakeup listeners added.
Going from here:
https://github.com/node-apn/node-http2/blob/dff41d97f010c9edb6369f02b382810a4f0bdbf3/lib/protocol/connection.js#L355

node v8.11.2

**Comment by alex-friedl** [comment]
Any chance of a fix for the 2.x version? Would be great for libraries that do not want to require node 8.x.x and can't update to v3 yet :)

**Comment by khflx** [comment]
@florianreinhart 
Hi.
I heard that http2 can solve this problem, and it seems that the v3.0.0-alpha1 version of this library has solved the memory leak problem?
Currently, http2 has been released with the release of node.js version 10.
It is no longer an experimental feature.
Can you post a version that fixes this bug?

**Comment by Muhand** [comment]
This bug still exist - a workaround is initiating a `provider` everytime and then shutting it off when you are done.

Something like this worked for me

```
import apn from 'apn';

const options = {
    token: {
         key: "path/to/APNsAuthKey_XXXXXXXXXX.p8",
         keyId: "key-id",
         teamId: "developer-team-id"
    },
    production: (process.env.NODE_ENV == "production") ? true : false
};

const sendNotification = (token) =>
   new Promise(
     (resolve,reject) => {
       let provider = new apn.Provider(options);
       let notification = new apn.Notification();

       notification.topic = "<your-app-bundle-id>";
       notification.alert = "hello world";

       provider.send(notification, token)
        .then( response => resolve(responsee))
        .catch( err => reject(err))
     }
   )
```


it is only a temporary solution until this is solved
would love to see a 2.x.x solution to this issue

**Comment by shashank34** [comment]
Memmory leak detected in node 8.11.3 version using apn 1.7.8 version on socket hangup or socket error, tls socket connection comes in active handles of node js environment . i think some event comes in closure and still alive not released. Please help if anyone had solution.

**Comment by ddoria921** [comment]
@florianreinhart Any chance we can get a new release out with HTTP/2 support now that Node has landed stable support? https://nodejs.org/api/http2.html#http2_http_2

**Comment by xfishernet** [comment]
node v11.7.0 same issue!

**Comment by nosuchip** [comment]
Confirm bug:

Node 10.16.0,
apn 2.2.0

Code to reproduce:
```
const apn = require('apn');
const path = require('path');

if (!process.env.PASSPHRASE) {
  console.error(`PASSPHRASE envvar must be defined`);
  process.exit(-1);
}

const cert_path = path.resolve(__dirname, '../cert/prod_cert.pem');
const key_path =  path.resolve(__dirname, '../cert/prod_key.pem');

const provider = new apn.Provider({
  cert: cert_path,
  key: key_path,
  passphrase: process.env.PASSPHRASE,
  production: true,
  ca: null
});

const devicesTokens = [
  '67xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx4d',
  'C6xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx7E',
  '33xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx4e'
];

(function() {
  var note = new apn.Notification();

  note.expiry = Math.floor(Date.now() / 1000) + 3600;
  note.badge = 3;
  note.sound = "ping.aiff";
  note.alert = "\uD83D\uDCE7 \u2709 Wanna something tasty";
  note.payload = {'messageFrom': 'Hannibal Lecter'};
  note.topic = "my.product.id";

    return provider.send(note, devicesTokens).then(result => {
      console.log(' result:', JSON.stringify(result, null, 2));
    }).catch(error => {
      console.error(' error:', error);
    });
})();
```

Let unattended after send (yes, it sends 2 notification and waits) it shows `(node:323) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 wakeup listeners added. U to increase limit` after short time.

**Comment by smhk** [comment]
Hey guys -

I'm simply **confused** about what to do to resolve this warning.

It's been some three years!

I'm more than happy to update anything on the EC2 ubuntu instance.

Is there a chance **someone could summarize** what to do to end the warning?

thanks!!

**Comment by bfelbo** [comment]
We've switched to https://github.com/AndrewBarba/apns2/tree/master and haven't looked back. The code is much cleaner and simpler. It just works :)

**Comment by smhk** [comment]
@bfelbo - funnily enough I was literally about to ask if anyone has tried apn2.  thanks for that report!!  

there's a weird github flag on APNS2, "build failed" (in black and red, just under the title "APNS2") - not an issue???

thanks again ...

**Comment by steveetm** [comment]
We also had a long-standing issue with our live server, as the load sporadically increased and after a few hours it leaked all the available memory. It was really struggling to figure this out, as notifications delivered successfully all the time and we were never able to repro it by manually sending notifications.

After we found this module even more suspicious we moved to apns2, every issue solved.
